### PR TITLE
Correct Buzz Aldrin's full name.

### PR DESCRIPTION
**Pull request by jaylett**

### CODE REVIEW

**Comment by georgebrock** [comment]
Looks good to me.

**Comment by jaylett** [comment]
@georgebrock if it looks good, do you want to merge it? :-)

**Comment by georgebrock** [comment]
@jaylett Oh, sure, sorry: I'm more used to a “PR author merges after review” workflow, rather than a “reviewer merges” workflow.

**Comment by jaylett** [comment]
@georgebrock ah, I've only ever worked in reviewer-merges, where it's often considered a sin to self-merge :-)

**Comment by georgebrock** [comment]
@jaylett Self-merge has some advantages: the author will probably have an easier time with merge conflicts, the author has a chance to squash commits and improve the messages, and things get merged quicker when the feedback is “fix this one small thing, then it's good to merge”

Happy to go either way on Spacelog repos, though.

**Comment by jaylett** [comment]
I've never sat down and planned a policy from scratch, only ever dropped into existing ones, so I haven't really thought this through :-)

Self-merge feels better to me in a lot of ways, so let's say that with a LGTM comment people can merge (but that doesn't stop a reviewer from merging if clean, which is generally faster).

**Pull request merged**
