### PR TITLE
Gemini IV TEC transcript

### PR DESCRIPTION
**Pull request by georgebrock**
This PR combines @jweather's work on the G4 TEC transcript with the work done on Kallisto, fixes the errors lognag found with the transcript, and converts it to Spacelog's format. I haven't read through the resulting transcript in any detail, but it does import cleanly.

To help with converting it to Spacelog's format, I also updated the MCShred tool to take a `-t` argument with the number of timestamp parts (e.g. 4 for day, hour, minute, second or 3 for hour, minute, second). This mirrors an argument that lognag already has.

https://trello.com/c/IEUa5ecs

### CODE REVIEW

**Comment by jweather** [comment]
I'm doing a read-through on this to fix some typos.  After [00:23:58:23] at line 9938, the formatting falls apart completely.

**Comment by jaylett** [comment]
It looks like after that point it's in the original format, and hasn't been passed through MCShred at all.

**Comment by georgebrock** [comment]
Oops, sorry about that. I got no warnings from MCShred or `make reindex`, checked over the first few pages in a browser, and assumed that everything was fine.

Turned out to be a problem with the MCShred's support for `HH:MM:SS` timestamps (as opposed to `DD:HH:MM:SS` timestamps). Once the hour value got above 24, MCShred stopped recognising it as a valid timestamp, and therefore just assumed that every subsequent line was a continuation of the previous one.

**Comment by georgebrock** [comment]
We should merge #241 into this branch, before we merge this into master.

**Comment by jweather** [comment]
There's major issues with p200 on... all of the multi-line messages are being treated as single-line messages with the remainder in _extra.  Suspect this will be easier to fix in import than for me to try to post-process it, so I will leave off here and update #241 with my p1-199 fixes.

**Comment by georgebrock** [comment]
@jweather Oops (again). This time the problem was that MCShred considers any line with any leading spaces as `_extra` rather than a continuation.

**Comment by georgebrock** [comment]
I've added the fixes from #241 (@jweather's detailed read through) as c6bcf62c5cac086c67a57d5a89c57230ee84dcd0, so the TEC transcript should be good.

Any objections to merging this?

**Pull request merged**
